#!/bin/bash

grep '<td>.\{1,\}<\/td>' $1 |
sed -n '0~2p' |
sed -E 's/^\s*|<[\/]?(td|u)>//g' |
sed 's/<.*>.*<\/.*>//g' |
tr "A-Z\`" "a-z\'" |
sed -E 's/\s|,\s/\n/g' |
sed '/^$/d' |
grep "^[pkmnwlhaeiou\']*$" |
sort -u